#Jeff Rouder, Local Data Extractor
extractData=function(d,code){
  stim=d$sender=="Stim"
  sessionID=d$observation[stim]
  ntrials=table(sessionID)
  codeTrials=rep(code,ntrials)
  targ=d[stim,]$targ
  back=d[stim,]$targ
  morph=d[stim,]$morph
  resp=d[stim,]$response
  rt=d[stim,]$duration
  out=data.frame(codeTrials,sessionID,targ,back,morph,resp,rt)
  colnames(out)=c("participantID",
                  "sessionID",
                  "targ",
                  "background",
                  "morph",
                  "resp",
                  "rt")
  return(out)}